apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: java-quarkus-egcrutir
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/java-quarkus-egcrutir:7af81e3314e90947d61a5a13bf87df9118d09c61@sha256:8be689abfc8d9fbe6832f2538c6d67d646c0ce06f601fa910aa6e53328a86dd5
        name: container-image  
